name: Build and Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            fyne_target: linux
            ext: ""
          - os: windows-latest
            goos: windows
            goarch: amd64
            fyne_target: windows
            ext: ".exe"
          - os: macos-latest
            goos: darwin
            goarch: arm64
            fyne_target: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Install fyne command
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Install Linux build deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev xorg-dev

      - name: Go mod tidy
        working-directory: ./src
        shell: bash
        run: go mod tidy

      - name: Package app
        working-directory: ./src/cmd/wago-init
        shell: bash
        run: fyne package --target ${{ matrix.fyne_target }}

      - name: Build binary
        working-directory: ./src
        shell: bash
        run: |
          mkdir -p ../build
          go build -ldflags -H=windowsgui -o "../build/wago-init-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}" ./cmd/wago-init

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wago-init-${{ matrix.fyne_target }}-${{ matrix.goarch }}
          path: build/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}