name: Build and Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            fyne_target: linux
            ext: ""
          - os: windows-latest
            goos: windows
            goarch: amd64
            fyne_target: windows
            ext: ".exe"
          - os: macos-latest
            goos: darwin
            goarch: arm64
            fyne_target: darwin
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Install fyne command
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Build binary
        working-directory: ./src
        run: |
          go mod tidy
          fyne package --target ${{ matrix.fyne_target }}
          go build -o "../build/wago-init-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}" ./cmd/wago-init

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wago-init-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
